### ISSUE TITLE
"Overriding timings"?

### ISSUE THREAD

**Issue by janpio** [sd2k/newrelic#9]
Nice project!

What exactly does (or will) "Overriding timings" refer to in the list of features?

**Comment by sd2k** [comment]
Hi! That refers to the ability to explicitly set the timing of a transaction ([C SDK link](https://newrelic.github.io/c-sdk/libnewrelic_8h.html#aa10391e95324811de986b486402b55da)) or a segment ([C SDK link](https://newrelic.github.io/c-sdk/libnewrelic_8h.html#a3a803e3956f754082fb8aaee9154b158)). Those functions have bindings in newrelic-sys but the functionality isn't exposed in this crate yet, simply because I never needed it. PRs would be welcome to add it in though - I can't imagine it being hard!

**Comment by janpio** [comment]
Oh wow, that is some handy functionality - shame it is not exposed [in other NR SDKs like node](https://github.com/newrelic/node-newrelic/issues/385).

Not sure we will go with New Relic in the end, but if we do this might come in handy for the external pieces that can not send instrumentation data by themselves.
